const { userLoginValidator } = require("../helpers");
const { comparePass } = require("../helpers/hashPass");
const catchAsyncWrapper = require("../helpers/catchAsyncWrapper");
const CustomError = require("../helpers/CustomError");

const User = require("../models/user");

const validateLogin = () => {
  const func = catchAsyncWrapper(async (req, res, next) => {
    const { email, password } = req.body;
    const { error } = userLoginValidator(req.body);

    if (error) {
      const err = error.details[0].path[0];

      next(new CustomError(400, `Missing field ${err}`));
      return;
    }

    const user = await User.findOne({ email });

    if (!user) {
      next(new CustomError(401, "Email or password is wrong"));
      return;
    }

    if (!user.verify) {
      next(new CustomError(401, "Email not verified"));
      return;
    }

    const result = await comparePass(password, user.password);

    if (!result) {
      next(new CustomError(401, "Email or password is wrong"));
      return;
    }

    next();
  });

  return func;
};

module.exports = validateLogin;
